"""
LangGraph State Definition

Defines the TypedDict state that flows through the LangGraph pipeline.
This is the central data structure that all nodes read from and write to.
"""

from typing import TypedDict, Optional, List, Dict, Any
from typing_extensions import Annotated
import operator


class AgentState(TypedDict):
    """
    State object that flows through the LangGraph pipeline.
    
    Each node receives this state, modifies its relevant fields,
    and passes it to the next node in the DAG.
    """
    
    # ==================== INPUTS ====================
    # Raw product data loaded from JSON files
    raw_product_a: Dict[str, Any]
    raw_product_b: Dict[str, Any]
    
    # ==================== PARSED DATA ====================
    # Structured product models after parsing
    product_a: Optional[Dict[str, Any]]
    product_b: Optional[Dict[str, Any]]
    
    # ==================== LOGIC BLOCK OUTPUTS ====================
    # Results from pure-function logic blocks
    benefits_data: Optional[Dict[str, Any]]
    usage_data: Optional[Dict[str, Any]]
    ingredients_data: Optional[Dict[str, Any]]
    comparison_data: Optional[Dict[str, Any]]
    
    # ==================== LLM-GENERATED CONTENT ====================
    # Questions generated by LLM
    questions: Optional[List[Dict[str, str]]]
    
    # Page content generated by LLM agents
    faq_output: Optional[Dict[str, Any]]
    product_output: Optional[Dict[str, Any]]
    comparison_output: Optional[Dict[str, Any]]
    
    # ==================== PIPELINE STATUS ====================
    # Tracking flags
    outputs_written: bool
    errors: Optional[List[str]]
    execution_log: Annotated[List[str], operator.add]
