"""
Pydantic Schemas for LLM Structured Output

These models define the expected output format from LLM calls,
ensuring type-safe, validated responses.
"""

from typing import List, Optional, Literal
from pydantic import BaseModel, Field


# ==================== QUESTION GENERATION ====================

class Question(BaseModel):
    """A single generated question with category."""
    category: Literal["informational", "safety", "usage", "purchase", "comparison"] = Field(
        description="The category of the question"
    )
    question: str = Field(
        description="The question text"
    )


class QuestionSet(BaseModel):
    """Set of 15+ categorized questions generated by LLM."""
    questions: List[Question] = Field(
        description="List of 15+ generated questions across all categories",
        min_length=15
    )


# ==================== FAQ OUTPUT ====================

class FAQItem(BaseModel):
    """A single FAQ question-answer pair."""
    id: str = Field(description="Unique identifier like faq-001")
    category: str = Field(description="Question category")
    question: str = Field(description="The question")
    answer: str = Field(description="The answer generated by LLM")


class FAQOutput(BaseModel):
    """Complete FAQ page output."""
    productName: str
    generatedAt: str
    totalQuestions: int
    faqs: List[FAQItem] = Field(min_length=5)


# ==================== PRODUCT PAGE OUTPUT ====================

class BenefitsSection(BaseModel):
    """Structured benefits data."""
    items: List[str]
    primary: str
    count: int


class UsageSection(BaseModel):
    """Structured usage instructions."""
    instructions: str
    frequency: str
    quantity: str
    timing: Optional[str] = None


class PriceSection(BaseModel):
    """Price information."""
    amount: float
    currency: str


class ProductOutput(BaseModel):
    """Complete product page output."""
    productName: str
    concentration: str
    skinTypes: List[str]
    keyIngredients: List[str]
    benefits: BenefitsSection
    usage: UsageSection
    sideEffects: str
    price: PriceSection


# ==================== COMPARISON OUTPUT ====================

class ProductSummary(BaseModel):
    """Summary of a product for comparison."""
    name: str
    price: float
    benefits: List[str]
    ingredients: List[str]


class ComparisonDetails(BaseModel):
    """Detailed comparison between two products."""
    commonIngredients: List[str]
    uniqueToA: List[str]
    uniqueToB: List[str]
    priceDifference: float
    cheaperProduct: Literal["productA", "productB"]
    recommendation: str = Field(
        description="LLM-generated recommendation text explaining the comparison"
    )


class ComparisonOutput(BaseModel):
    """Complete comparison page output."""
    productA: ProductSummary
    productB: ProductSummary
    comparison: ComparisonDetails
